### ISSUE TITLE
Support for multiple proxies 

### ISSUE THREAD

**Issue by jnijland** [BebeDlaStreat/DiscordRankSync#1]
I tried the Bungeecord version of your plugin and I love it. I wish to implement it on my network. However, I run multiple proxies in my network (for scalability, it's based on Kubernetes). 

Unfortunately, when installed on all proxies, and command is given in Discord, it gives you the "This player is not online" error. This is probably due to the proxy which was first replying to the command not being the proxy where the user is online. 

Do you have any suggestion for a workaround or a solution? I bet there are more people with a multi proxy setup which would love to use a feature like this.

**Comment by jnijland** [comment]
Data between proxies is synchronized via the RedisBungee fork of ProxioDev (https://github.com/ProxioDev/RedisBungee). Maybe your plugin could hook into RedisBungee?

**Comment by Benoit-V** [comment]
Hi, thanks for your feedback, i will try to add RedisBungee compatibility in the next days, you can stay stuned about the update on my discord https://bebedlastreat.fr/discord

**Comment by jnijland** [comment]
Awesome! I'll join the Discord.
