### ISSUE TITLE
Error after player leaves the server

### ISSUE THREAD

**Issue by pjindras** [BebeDlaStreat/DiscordRankSync#5]
This issue occurs, when a player, who hasn't linked account yet leaves the server.

https://paste.gg/p/anonymous/7e9b453bebde4c97b6e74c7ce16fb90d

**Comment by pjindras** [comment]
+ there is one more issue which is constantly spamming my console
https://paste.gg/p/anonymous/bb943673aaa844b3a87d8e5dc8e66487

**Comment by Benoit-V** [comment]
https://github.com/BebeDlaStreat/DiscordRankSync/releases/tag/v1.8
the error was fixed but I didn't published a release
