### ISSUE TITLE
java.sql.SQLSyntaxErrorException: Unknown column 'name' in 'field list'

### ISSUE THREAD

**Issue by ruk13xa** [BebeDlaStreat/DiscordRankSync#6]
3|lobby    | [00:59:39 WARN]: java.sql.SQLSyntaxErrorException: Unknown column 'name' in 'field list'
3|lobby    | [00:59:39 WARN]:   at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112)
3|lobby    | [00:59:39 WARN]:   at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
3|lobby    | [00:59:39 WARN]:   at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:938)
3|lobby    | [00:59:39 WARN]:   at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1106)
3|lobby    | [00:59:39 WARN]:   at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1045)
3|lobby    | [00:59:39 WARN]:   at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1369)
3|lobby    | [00:59:39 WARN]:   at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1030)
3|lobby    | [00:59:39 WARN]:   at ShopGUIPlus-1.97.1.jar//net.brcdev.shopgui.database.DataManager.lambda$executeQuery$0(DataManager.java:69)
3|lobby    | [00:59:39 WARN]:   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
3|lobby    | [00:59:39 WARN]:   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
3|lobby    | [00:59:39 WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
3|lobby    | [00:59:39 WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
3|lobby    | [00:59:39 WARN]:   at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Benoit-V** [comment]
May be giving some context and being less tough would be better

**Comment by Benoit-V** [comment]
this error is not from my plugin ?

**Comment by ruk13xa** [comment]
oops sorry my bad
